### ISSUE TITLE
GA4 doesn't match conversion with existing data

### ISSUE THREAD

**Issue by JoostWan** [br33f/php-GA4-Measurement-Protocol#24]
I don't know if this is an issue or a wrong call on our side. But we used this package from e-commerce system Magento. When a payment is made we send a call to the measurement protocol. We saved also the `client_id` to the order. When we do the call to the measurement protocol we send also the client ID. Conversion is visible in GA4 but it's not matched with an existing sessie. Did some research and found some information on this site; 

How we can set the **Session ID** and timestamp with this package to send this data with the client id to the measurement protocol. 

https://www.simoahava.com/analytics/session-attribution-with-ga4-measurement-protocol/

![Screenshot 2023-03-14 at 21 56 29](https://user-images.githubusercontent.com/5435412/225134305-3a711a65-8636-41e7-bafc-b01e1a62670d.png)

**Comment by br33f** [comment]
@JoostWan 
You can set any data to an event object:
```
$eventName = 'example_event'; 
$anyEventData = new BaseEvent($eventName);
$anyEventData
    ->setMethod('Twitter')
    ->setContentType('Post')
    ->setItemId('example_item_id')
    ->setAnyParamYouWish('test'); // means 'any_param_you_wish' is set
```

So you can set both **session_id** and **timestamp** parameter this way.

Alternatively, if you wish not to use PHP magic methods, you can set params explicitly by calling:
`$anyEventData->setParamValue('param_name', 'param_value');`

Hope it helps.

**Comment by JoostWan** [comment]
@br33f Thanks!

**Comment by Luxato** [comment]
@JoostWan Hey, I am currently solving exactly the same problem, all my conversions are attributed as "direct" even though most of them come from "Paid" and "Organic".

Can I ask if I have to send the whole value of the cookie with the 2 letters in the beginning?
For example for _ga, should it be GA1.1.1938356095.1686127670 or just 1.1.1938356095.1686127670
Same for _ga_<measurement_id>, GS1.1.1686131519.2.1.1686131605.60.0.0 or 1.1.1686131519.2.1.1686131605.60.0.0.

Thanks for reply.

**Comment by Fnizou** [comment]
Well done it's all there!

Thanks to you,

**Comment by Luxato** [comment]
But I still can't attribute them with the correct sessions, every conversion is still "direct" ffs.
Have you eventually made it run @basepack ?

**Comment by Fnizou** [comment]
You have use :
$eventData->setParamValue('session_id', 'session-id-here');
Or
$eventData->setSessionId('session-id-here');
?

**Comment by Luxato** [comment]
@Fnizou Yes, I am using this 

```
if (strpos(($browserData['ga4_session_id'] ?? ''), '.') !== false) {
                $parts = explode(".", $customerBrowserData['ga4_session_id']);
                $ga4_session_id = $parts[2]; // Output: 1686042977
}
```            

```
$purchaseEventData->setParamValue('session_id', $ga4_session_id);
```

**Comment by Fnizou** [comment]
@Luxato I will try on my side in the next few days,

can you try to force the typing:
$purchaseEventData->setParamValue('session_id', **(int)**$ga4_session_id);

I have already had a problem with the transaction_id being raised because of this,

we stay informed

**Comment by Fnizou** [comment]
@Luxato on my side I just set up this,
and I think "session_id" it's a (string) and not (int),

if( !is_null($row['id_session_ga4']) ){
   $purchaseEventData->setParamValue('session_id', (string)$row['id_session_ga4']);
}

I wait 24 hours

**Comment by Luxato** [comment]
I've been investigating my data in BigQuery. It seems like it gets there fine.
But when I tried to search by client id, there are no prior events.
Then I checked other events and I've noticed that the client id is encoded.

![image](https://github.com/br33f/php-GA4-Measurement-Protocol/assets/15067643/79bc6a54-fe99-4506-96ca-b46ea46c435d)

Whereas my conversions have format taken from the cookie
![image](https://github.com/br33f/php-GA4-Measurement-Protocol/assets/15067643/62b897a5-7908-4158-80fe-fcc261696d9a)

Any ideas why it's being encoded?

**Comment by Luxato** [comment]
![image](https://github.com/br33f/php-GA4-Measurement-Protocol/assets/15067643/1a6a73a2-c455-4178-b211-a59944cce0a9)

Found this setting in the GTM server container :P, the client id is not being encoded anymore

**Comment by Kurtafterjim** [comment]
Hi,
I have the same problem: in the "User acquisition" report, purchases are correctly attributed to the various channels, while in the "Traffic acquisition" report, all conversions are attributed to the "Unassigned" channel group.
I realized the reason is that I set setClientId() but not setSessionId().

However, I didn't understand how to extract the Session ID value.
Can you help me please?
Thank you
