### ISSUE TITLE
Set purchase transaction_id

### ISSUE THREAD

**Issue by Kurtafterjim** [br33f/php-GA4-Measurement-Protocol#28]
Hello guys!
There is a way to set the GA4 parameter "transaction_id" ?

Thanks a lot

**Comment by Luxato** [comment]
Hey!

Yes, you can set transaction_id on the purchase event.

`// Create Event Data
$purchaseEventData = new PurchaseEvent();
$purchaseEventData
    ->setValue(250.00)
    ->setTransactionId('T_12345')
    ->setCurrency('USD');`
    
Hope it helps.
