### ISSUE TITLE
Send Only purchase with API, lose session info and traffic source

### ISSUE THREAD

**Issue by Fnizou** [br33f/php-GA4-Measurement-Protocol#33]
Hi,

I send only event purchase with API, the other tags are by the browser,
I have the conversion on the reports, but i lose session info and traffic source on report GA4, 

id google is however well informed:
$baseRequest->setClientId($CLIENT_ID); // From infos Cookies

do you have an idea  ?

Thank you,

**Comment by Fnizou** [comment]
I think the nuance is between the CID and SID,
not sure if the API supports the SID,
What do you think ?

**Comment by basepack** [comment]
Yea with my ideas above you get the clientId, not a session id. So I was talking about _ga in the cookies below:
<img width="761" alt="image" src="https://github.com/br33f/php-GA4-Measurement-Protocol/assets/939500/70d46154-d597-4f35-980e-42aa0e30e61b">

You want the one on top, and what is marked in red is the session id which you can get, an example here: https://dodov.dev/blog/how-to-get-google-analytics-session-id-and-session-number

And yes can also supply a session_id via the measurement api as you can see here: https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=gtag#recommended_parameters_for_reports

There is no setSessionId parameter, but you can set it like this `$eventData->setSessionId('session-id-here');` explained by br33f here: https://github.com/br33f/php-GA4-Measurement-Protocol/issues/24#issuecomment-1476889861

**Comment by Fnizou** [comment]
Well done it's all there!

Thanks to you,

**Comment by neway** [comment]
I'm using BigQuery to lookup client ID and session id (using streaming during dev for fast turnaround) - and am really struggling to get anything apart from a now() timestamp in the event_timestamp field.   I'm pushing a purchase event, with a timestamp_macros field:

Anybody got this working?

{
  "client_id": "862862246.1741960049",
  "timestamp_micros": "1741965617589479",
  "non_personalized_ads": false,
  "events": [
    {
      "name": "purchase",
      "params": {
        "items": [
          {
            "item_id": "623e2a0df01bab7421174bcc",
            "item_name": "Afternoon Tea",
            "affiliation": "",
            "coupon": "",
            "currency": "GBP",
            "discount": 0,
            "index": 0,
            "item_brand": "",
            "item_category": "",
            "item_category2": "",
            "item_category3": "",
            "item_category4": "",
            "item_category5": "",
            "item_list_id": "",
            "item_list_name": "",
            "item_variant": "",
            "location_id": "",
            "price": 32.5,
            "quantity": 2,
            "creative_name": "",
            "creative_slot": "",
            "promotion_id": "",
            "promotion_name": ""
          }
        ],
        "currency": "GBP",
        "transaction_id": "event-build-2",
        "value": 65,
        "session_id": 1741962016,
        "debug_mode": 1
      }
    }
  ]
}
