### ISSUE TITLE
Asynchronous events

### ISSUE THREAD

**Issue by coccoinomane** [br33f/php-GA4-Measurement-Protocol#34]
Hello,
First of all, thank you very much for this great library!  You saved me a lot of time :-)

The old Iconic library supported sending async requests to the measurement protocol.
It used to work with a handy setter: `setAsyncRequest(true)`.
Is there something similar in your package?

Thanks!

**Comment by br33f** [comment]
Hi,
There are no async requests implemented in this library at the moment, but might  be the part of next releases.
