### ISSUE TITLE
Debugging with Google Analytics DebugView

### ISSUE THREAD

**Issue by joerg-thode** [br33f/php-GA4-Measurement-Protocol#38]
Does anyone have a tip on how to use the DebugView in GoogleAnalytics-Account with this repro? 

My Problem is that no errors occur by ...  (purchase)

$baseRequest->addEvent($eventData);               
$debugResponse  = $ga4Service->sendDebug($baseRequest);
$ResponseCode   = $debugResponse->getStatusCode();
$ResponseMsg    = $debugResponse->getValidationMessages();
$ResponseData   = $debugResponse->getData();

ResponseCode 200

I tried to set this before, but i can see nothing @ DebugView

$eventData = new PurchaseEvent();
$eventData->setParamValue("debug_mode", "1");

**Comment by FabianoLothor** [comment]
I didn't dig into this yet, but you probably need to specify the debug_mode in the list of parameters.

![image](https://github.com/br33f/php-GA4-Measurement-Protocol/assets/2192995/29e698ab-db30-4000-9e7f-256c2d5553ba)

**Comment by br33f** [comment]
```
$eventData = new PurchaseEvent();
$eventData->setParamValue("debug_mode", "1");
```

What you mentioned in your comment is a correct way to set a param "debug_mode" in event parameters.
If it does not work, you should look for the problem elsewhere, but the code itself is correct.

I belive you can also set a debug_mode globaly in Google Analytics data source configuration.
