### ISSUE TITLE
Fix return type of debug request

### ISSUE THREAD

**Issue by wernight** [br33f/php-GA4-Measurement-Protocol#43]
https://github.com/br33f/php-GA4-Measurement-Protocol/blob/c305dd78c36408b053ac8e62fc214d704121473a/src/Service.php#L118
 should say that it returns a [DebugResponse.php](https://github.com/br33f/php-GA4-Measurement-Protocol/blob/c305dd78c36408b053ac8e62fc214d704121473a/src/Dto/Response/DebugResponse.php#L23) instead of `BaseResponse`.

**Comment by br33f** [comment]
It will be changed in v0.1.5 version.
