### ISSUE TITLE
non_personalized_ads not updated in Mesurement API

### ISSUE THREAD

**Issue by AlexisPPLIN** [br33f/php-GA4-Measurement-Protocol#47]
Hello everyone !

When using this lib, something weird showed up in Google Analytics DebugView :

![image](https://github.com/br33f/php-GA4-Measurement-Protocol/assets/82219937/e9658e69-fc0e-429b-99e8-15a12b08075e)

`non_personalized_ads` seems to be updated to `1` even when using  `$request->setNonPersonalizedAds(false)`.

NB : I'm using my fork #46 with the  `non_personalized_ads = false` fix.

## More details

- `page_view` generated by https://www.googletagmanager.com/gtag/js.
```js
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('consent', 'default', {
        'ad_storage': 'denied',
        'ad_user_data': 'denied',
        'ad_personalization': 'denied',
        'analytics_storage': 'denied',
        'wait_for_update': 500
    });

    gtag('js', new Date());
    gtag('config', 'REDACTED', { 'debug_mode': true });
</script>
<script async src='https://www.googletagmanager.com/gtag/js?id=REDACTED'></script>
```
- `add_to_cart` generated by this lib.
```php
$service = new Service(API_SECRET);
$service->setMeasurementId(REDACTED);

$request = new BaseRequest();
$request->setClientId(CLIENT_ID);
$request->setNonPersonalizedAds(false);

$consent = new ConsentProperty(ConsentCode::DENIED, ConsentCode::DENIED);
$request->setConsent($consent);
// ...
$event->setDebugMode(true);
```

Payload send to Mesurement API : 
```json
{
    "client_id": "CLIENT_ID",
    "events": [
        {
            "name": "add_to_cart",
            "params": {
                "items": [
                    {
                        "item_id": "ITEM_ID",
                        "item_name": "ITEM_NAME",
                        "quantity": 1
                    }
                ],
                "session_id": "SESSION_ID",
                "debug_mode": true
            }
        }
    ],
    "non_personalized_ads": false,
    "consent": {
        "ad_user_data": "DENIED",
        "ad_personalization": "DENIED"
    }
}
```

**Comment by Pavliczech** [comment]
Hello,
you need to change `$request->setNonPersonalizedAds(false);` to `true`. Then the value `non_personalized_ads = 0` will be sent to GA. I tried modifying it in various ways in `user_data`, but nothing worked. When I adjust it this way, it works correctly for me.

**Comment by AlexisPPLIN** [comment]
Hey @Pavliczech 

I've already tried this and nothing changed :disappointed: 

Even with official Google debug tool https://ga-dev-tools.google/ga4/event-builder/ this seems quite random.

Response from Google Analytics supports doesn't help either, they do not understand my issue (and It's quite frustrating).

Thanks anyway :+1:

**Comment by br33f** [comment]
@AlexisPPLIN Your pull request is now in v0.1.5 version
