### ISSUE TITLE
Full documentation link goes to 'Service Unavailable' page

### ISSUE THREAD

**Issue by nd3w** [br33f/php-GA4-Measurement-Protocol#48]
Full documentation link: https://developers.google.com/analytics/devguides/collection/protocol/ga4 is unavailable.

![image](https://github.com/br33f/php-GA4-Measurement-Protocol/assets/2328329/c10b6c17-dc83-4a8b-ac51-aaea1f742d10)

**Comment by br33f** [comment]
It seems to work now. Perhaps it was just a temporary unavailability.
