### ISSUE TITLE
FR: Support Guzzle 7

### ISSUE THREAD

**Issue by FrittenKeeZ** [br33f/php-GA4-Measurement-Protocol#6]
Please add support for Guzzle 7

**Comment by lizardslair** [comment]
Seconding this request as the ^6.x.x restriction is preventing install in my project because we have another package that is using ^7. Thank you for creating this tool!

**Comment by br33f** [comment]
[v](https://github.com/br33f/php-GA4-Measurement-Protocol/pull/7)

Thank you @lizardslair !
